# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pollen Climate Model Intercomparison Project
email: goring@wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  The Pollen Climate Model Intercomparison project is part of a PAGES funded initiative, 
  to provide a statistical framework for evaluating fit, mismatch and artifacts of 
  pollen-based climate reconstruction models
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://PCMIP.github.io" # the base hostname & protocol for your site
github_username:  PCMIP

# Build settings
markdown: kramdown
